### ISSUE TITLE
trying to start your app but...

### ISSUE THREAD

**Issue by guillaumedufour** [vikkio88/ads-cli#1]
![sans titre](https://user-images.githubusercontent.com/28460677/40537179-9474d60e-600e-11e8-8c1e-c967340c6361.png)
Hello i'm trying to launch your app but i can't.
I'm a beginner in js app.
I cloned your repo, installed all the dependencies with yarn install, and tried "node index.js".

What's wrong ?

**Comment by vikkio88** [comment]
hi there, the app is supposed to work with node >=9.
I am not maintaining this project anymore, the lib though is used in here https://github.com/vikkio88/ads-react

**Comment by vikkio88** [comment]
@guillaumedufour actually scrap that ↑ I saw the code now, I did transpile it, try to run
```
yarn start
```
